name: Build image and deploy to ECR

on:
  push:
    branches:
    - main
    paths:
    - src/demo-service/**

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_KEY }}

      - name: configureawscredentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.ASSUME_ROLE }}
          role-session-name: samplerolesession
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Build, tag, and push image to Amazon ECR
        working-directory: ./src/demo-service
        env:
          REGISTRY: ${{ vars.REGISTRY_URL }}
          REGISTRY_ALIAS: ${{ vars.REGISTRY_ALIAS }}
          REPOSITORY: ${{ vars.REGISTRY_REPOSITORY }}
          ## Required because ecr-public is only available on this region
          REGION: us-east-1
        run: |
          aws ecr-public get-login-password --region $REGION | docker login --username AWS --password-stdin $REGISTRY
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY .
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY

