name: Build image and deploy to ECR

on:
  push:
    branches: [feat/use-terraform]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_KEY }}

      - name: configureawscredentials
        uses: aws-actions/configure-aws-credentials@v2
        env:
          AWS_DEFAULT_PROFILE: user1
          AWS_DEFAULT_REGION: us-east-2
        with:
          role-to-assume: arn:aws:iam::859703558734:role/github-action-role
          role-session-name: samplerolesession
          aws-region: ${{env.AWS_DEFAULT_REGION}}

      - name: Setup Profile
        env:
          PROFILE_NAME: user1
        run: |
          aws configure set region ${{ env.REGION }} --profile ${{ env.PROFILE_NAME }}
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile ${{ env.PROFILE_NAME }}
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile ${{ env.PROFILE_NAME }}
          aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile ${{ env.PROFILE_NAME }}


      - name: Run AWS test commands
        run: |
          aws configure list --profile user1

