name: Build image and deploy to ECR

on:
  push:
    branches: [feature/login-aws-with-assumerole]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_KEY }}

      - name: configureawscredentials
        uses: aws-actions/configure-aws-credentials@v2
        env:
          AWS_DEFAULT_REGION: us-east-2
        with:
          role-to-assume: arn:aws:iam::859703558734:role/github-action-role
          role-session-name: samplerolesession
          aws-region: ${{env.AWS_DEFAULT_REGION}}

      - name: Build, tag, and push image to Amazon ECR
        env:
          REGISTRY: public.ecr.aws
          REGISTRY_ALIAS: a3b1j4l7
          REPOSITORY: aws-fargate-demo-registry
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REGISTRY
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG

